### PR TITLE
Import `OaImporter` subjects inside the interested importer

### LINKED ISSUE #458: Revert the inheritance from AbstarctOaImporter
### Description
Remove the inheritance from AbstarctOaImporter if the implementation in the datasource does not reflect it. This class should be used only from Census importer atm as only there `importDatasource` has the right implementation that imports the OaImporter subjects inside the method.

### Error lof for TrafficCounter
```
uk.org.tombolo.importer.ConfigurationException: Unknown DatasourceId:trafficCounter
        at uk.org.tombolo.importer.AbstractImporter.importDatasource(AbstractImporter.java:95)
        at uk.org.tombolo.importer.AbstractOaImporter.importDatasource(AbstractOaImporter.java:28)
        at uk.org.tombolo.execution.DataExportEngine.importDatasource(DataExportEngine.java:92)
        at uk.org.tombolo.execution.DataExportEngine.execute(DataExportEngine.java:47)
        at uk.org.tombolo.DataExportRunner.run(DataExportRunner.java:56)
        at uk.org.tombolo.DataExportRunner.main(DataExportRunner.java:32)
Exception in thread "main" java.lang.RuntimeException
        at uk.org.tombolo.DataExportRunner.run(DataExportRunner.java:59)
        at uk.org.tombolo.DataExportRunner.main(DataExportRunner.java:32)
:runExport FAILED
```

### PR DESCRIPTION
**Pull request by lorenaqendro**
### Description
Fixes the bug of `datasourceId` not recognised when importing `OaImporter` subjects inside other importers. This PR fixes the bug but also adds support for a different scenario not included in the master atm.
In the current status an importer that uses existing subjects defined in `OaImporter` would import them internally even if not defined as datasources in the recipe. This will happen only if the `OaImporter` subject type they need is a top level subject in the recipe. This means that if the top subject is `lsoa` and the importer needs existing `msoa` subjects, they will not be imported. This PR takes care also of the latter.

Fixes #458

### CODE REVIEW

**Comment by lorenaqendro** [comment]
Checking the failures 💃

**Comment by lorenaqendro** [comment]
@arya-hemanshu need a review here. Thanks!

File: src/main/java/uk/org/tombolo/importer/londondatastore/AbstractLondonDatastoreImporter.java [hunk 1]
```diff
@@ -17,4 +21,9 @@ public Provider getProvider() {
         return PROVIDER;
     }
 
+    @Override
+    protected List<String> getOaDatasourceIds() {
+        return Collections.singletonList(OaImporter.OaType.localAuthority.datasourceSpec.getId());
+    }
```
Comment (arya-hemanshu) [inline src/main/java/uk/org/tombolo/importer/londondatastore/AbstractLondonDatastoreImporter.java]: this means that from 

```
get-localauthority-data-for-traffic-counters.json, i could remove

"importerClass": "uk.org.tombolo.importer.ons.OaImporter",
 "datasourceId": "localAuthority"
```
but wont this restrict user to compute on localAuthority only and not with msoa or lsoa?

File: src/main/java/uk/org/tombolo/importer/ons/CensusImporter.java [hunk 2]
```diff
@@ -43,12 +44,32 @@
...
+
+        return Collections.emptyList();
+    }
+
+    @Override
+    protected List<String> getOaDatasourceIds() {
+        return subjectRecipes.stream().filter(subjectRecipe ->
+            EnumUtils.isValidEnum(OaImporter.OaType.class, subjectRecipe.getSubjectType())).map(subjectRecipe ->
+                subjectRecipe.getSubjectType()).collect(Collectors.toCollection(ArrayList::new));
     }
```
Comment (arya-hemanshu) [inline src/main/java/uk/org/tombolo/importer/ons/CensusImporter.java]: I believe with this change we could now remove 

```
        "importerClass": "uk.org.tombolo.importer.ons.OaImporter",
        "datasourceId": "lsoa"
```
from renting-percentiles-for-leeds-normalised-nationally.json.
However, upon doing that and running the recipe the system didn't try to download the lsoa boundaries. But when added the above code segment back to datasources, DC did download the lsoa boundaries.

Please let me know if this is not how this was suppose to be used.

File: src/main/java/uk/org/tombolo/importer/ons/ONSClaimantsImporter.java [hunk 3]
```diff
@@ -64,6 +64,11 @@ public DatasourceSpec getDatasourceSpec(String datasourceIdString) throws Except
         return DatasourceId.valueOf(datasourceIdString).datasourceSpec;
     }
 
+    @Override
+    protected List<String> getOaDatasourceIds() {
+        return Collections.singletonList(OaImporter.OaType.lsoa.datasourceSpec.getId());
+    }
```
Comment (arya-hemanshu) [inline src/main/java/uk/org/tombolo/importer/ons/ONSClaimantsImporter.java]: wont this restrict user to only work with lsoa boundaries?

Comment (arya-hemanshu) [reply src/main/java/uk/org/tombolo/importer/ons/ONSClaimantsImporter.java]: It would be good, if we could have a recipe that tests this.

File: src/main/java/uk/org/tombolo/importer/ons/ONSWagesImporter.java [hunk 4]
```diff
@@ -138,6 +139,11 @@ public DatasourceSpec getDatasourceSpec(String datasourceIdString) throws Except
         return DatasourceId.valueOf(datasourceIdString).datasourceSpec;
     }
 
+    @Override
+    protected List<String> getOaDatasourceIds() {
+        return Collections.singletonList(OaImporter.OaType.localAuthority.datasourceSpec.getId());
+    }
+
```
Comment (arya-hemanshu) [inline src/main/java/uk/org/tombolo/importer/ons/ONSWagesImporter.java]: I believe this would restrict user to work only with localAuthority boundaries

File: src/test/java/uk/org/tombolo/importer/ons/CensusImporterTest.java [hunk 5]
```diff
@@ -134,7 +134,7 @@ public void importDatasourcePOD() throws Exception {
         importer.importDatasource(POD_ID, null, null, null, subjectRecipes, false);
         assertEquals(0, importer.getSubjectCount());
         assertEquals(0, importer.getFixedValueCount());
-        assertEquals(24, importer.getTimedValueCount());
+        assertEquals(16, importer.getTimedValueCount());
```
Comment (arya-hemanshu) [inline src/test/java/uk/org/tombolo/importer/ons/CensusImporterTest.java]: why is it getting less values now?

**Comment by lorenaqendro** [comment]
@arya-hemanshu this implementation does not restrict the user to work only with certain geographies but allows to import from OA the subjects needed to the importer to materialise the data in the database. Only in the case of the CensusImporter it depends from the recipe subject, in the other case its related to which geography level the datasource provides the data.
E.g. the `ONSWagesImporter` needs the  `la` subjects and this is independent from the subject specified in the top of the recipe.

So what the user does not need to do anymore is to know that the `ONSWagesImporter` needs the `la` subjects.
E.g.
```
{
  "dataset": {
    "subjects": [
      {
        // We output each LSOA whose name starts with 'Leeds'
        "subjectType": "lsoa",
        "provider": "uk.gov.ons",
        "matchRule": {
          "attribute": "name",
          "pattern": "Leeds%"
        }
      }
    ],
    "datasources": [
      {
        // Importer for the geographic objects for all LSOAs in the UK
        "importerClass": "uk.org.tombolo.importer.ons.OaImporter",
        "datasourceId": "lsoa"
      },
      {
        // Importer for the ONS Census dataset for renting
        "importerClass": "uk.org.tombolo.importer.ons.ONSWagesImporter",
        "datasourceId": "wages"
      }
    ],
```

File: src/main/java/uk/org/tombolo/importer/ons/ONSWagesImporter.java (hunk 4 above)
Comment (lorenaqendro) [reply src/main/java/uk/org/tombolo/importer/ons/ONSWagesImporter.java]: Please see the general comment.

File: src/main/java/uk/org/tombolo/importer/ons/ONSClaimantsImporter.java (hunk 3 above)
Comment (lorenaqendro) [reply src/main/java/uk/org/tombolo/importer/ons/ONSClaimantsImporter.java]: Please see the general comment.

File: src/main/java/uk/org/tombolo/importer/ons/CensusImporter.java (hunk 2 above)
Comment (lorenaqendro) [reply src/main/java/uk/org/tombolo/importer/ons/CensusImporter.java]: Checking this now.

File: src/main/java/uk/org/tombolo/importer/londondatastore/AbstractLondonDatastoreImporter.java (hunk 1 above)
Comment (lorenaqendro) [reply src/main/java/uk/org/tombolo/importer/londondatastore/AbstractLondonDatastoreImporter.java]: Please see the general comment.

**Comment by arya-hemanshu** [comment]
So, basically here we are only eliminating the need for another datasource line

```
        "importerClass": "uk.org.tombolo.importer.ons.OaImporter",
        "datasourceId": "localAuthority"
```

but user would still need to give this, in case of other granularities 
```
        "importerClass": "uk.org.tombolo.importer.ons.OaImporter",
        "datasourceId": "lsoa"
```
Correct me if i misunderstood it

**Comment by lorenaqendro** [comment]
I wouldn't say `we are only eliminating the need for another datasource line`, because there could be more than one, but if the user needs to get a specific subject needs to specify it in the datasource. This only imports `OaImporter` subjects inside the interested importer.

If what you had in mind is: The user does not need to import the subjects from Oa anymore at all or any subjects these are other issues. If what you expected is the aforementioned there could be created 2 enhancement issues:
- [ ] understand which `oa` subject is needed so the user does not need to include it as a datasource at all in the recipe. Good idea, but why are the oa subjects different to the other subjects to not be imported automatically? Needs to be explained carefully in the documentation. Might still be misleading if my subject is trafficCount for example with the geo match rule of lsoas.
- [ ] Import all the subjects in the subject session independently from the type. Requires more development time as it's easier for the OaImporter as we know the class, we do not have values or geography restrictions.

File: src/main/java/uk/org/tombolo/importer/ons/CensusImporter.java (hunk 2 above)
Comment (lorenaqendro) [reply src/main/java/uk/org/tombolo/importer/ons/CensusImporter.java]: aha, got it :dancing_men: . making the changes.

**Comment by arya-hemanshu** [comment]
I would prefer first point as second point would be to much downloading and processing and maybe user doesn't use those.
But yeah you are right lets put an issue as an enhancement.
